# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ace05df190f60e2e3e865aee5a652ac8318dd5bcdbc123b795aa165f30b75aea1622fbe0cfa9e53f7296d68202ac0dcddb12cbd9035d71afbe55eb7006bab57c

test:
  secret_key_base: c7f6ab9d23fa6422e3de43fd190f1b24bb68b10b99c9259cd15872213a8cedb22b191eaebc28d0e04d820bb5d20fc916483b2fd355961c8ad19df605dbfecd8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
